// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gropanda

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/testcontainers/testcontainers-go"
)

// NewMockPandaContainer creates a new instance of MockPandaContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPandaContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPandaContainer {
	mock := &MockPandaContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPandaContainer is an autogenerated mock type for the PandaContainer type
type MockPandaContainer struct {
	mock.Mock
}

type MockPandaContainer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPandaContainer) EXPECT() *MockPandaContainer_Expecter {
	return &MockPandaContainer_Expecter{mock: &_m.Mock}
}

// AdminAPIAddress provides a mock function for the type MockPandaContainer
func (_mock *MockPandaContainer) AdminAPIAddress(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AdminAPIAddress")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPandaContainer_AdminAPIAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminAPIAddress'
type MockPandaContainer_AdminAPIAddress_Call struct {
	*mock.Call
}

// AdminAPIAddress is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPandaContainer_Expecter) AdminAPIAddress(ctx interface{}) *MockPandaContainer_AdminAPIAddress_Call {
	return &MockPandaContainer_AdminAPIAddress_Call{Call: _e.mock.On("AdminAPIAddress", ctx)}
}

func (_c *MockPandaContainer_AdminAPIAddress_Call) Run(run func(ctx context.Context)) *MockPandaContainer_AdminAPIAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPandaContainer_AdminAPIAddress_Call) Return(s string, err error) *MockPandaContainer_AdminAPIAddress_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPandaContainer_AdminAPIAddress_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockPandaContainer_AdminAPIAddress_Call {
	_c.Call.Return(run)
	return _c
}

// HTTPProxyAddress provides a mock function for the type MockPandaContainer
func (_mock *MockPandaContainer) HTTPProxyAddress(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HTTPProxyAddress")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPandaContainer_HTTPProxyAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTPProxyAddress'
type MockPandaContainer_HTTPProxyAddress_Call struct {
	*mock.Call
}

// HTTPProxyAddress is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPandaContainer_Expecter) HTTPProxyAddress(ctx interface{}) *MockPandaContainer_HTTPProxyAddress_Call {
	return &MockPandaContainer_HTTPProxyAddress_Call{Call: _e.mock.On("HTTPProxyAddress", ctx)}
}

func (_c *MockPandaContainer_HTTPProxyAddress_Call) Run(run func(ctx context.Context)) *MockPandaContainer_HTTPProxyAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPandaContainer_HTTPProxyAddress_Call) Return(s string, err error) *MockPandaContainer_HTTPProxyAddress_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPandaContainer_HTTPProxyAddress_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockPandaContainer_HTTPProxyAddress_Call {
	_c.Call.Return(run)
	return _c
}

// KafkaSeedBroker provides a mock function for the type MockPandaContainer
func (_mock *MockPandaContainer) KafkaSeedBroker(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for KafkaSeedBroker")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPandaContainer_KafkaSeedBroker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KafkaSeedBroker'
type MockPandaContainer_KafkaSeedBroker_Call struct {
	*mock.Call
}

// KafkaSeedBroker is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPandaContainer_Expecter) KafkaSeedBroker(ctx interface{}) *MockPandaContainer_KafkaSeedBroker_Call {
	return &MockPandaContainer_KafkaSeedBroker_Call{Call: _e.mock.On("KafkaSeedBroker", ctx)}
}

func (_c *MockPandaContainer_KafkaSeedBroker_Call) Run(run func(ctx context.Context)) *MockPandaContainer_KafkaSeedBroker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPandaContainer_KafkaSeedBroker_Call) Return(s string, err error) *MockPandaContainer_KafkaSeedBroker_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPandaContainer_KafkaSeedBroker_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockPandaContainer_KafkaSeedBroker_Call {
	_c.Call.Return(run)
	return _c
}

// SchemaRegistryAddress provides a mock function for the type MockPandaContainer
func (_mock *MockPandaContainer) SchemaRegistryAddress(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SchemaRegistryAddress")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPandaContainer_SchemaRegistryAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SchemaRegistryAddress'
type MockPandaContainer_SchemaRegistryAddress_Call struct {
	*mock.Call
}

// SchemaRegistryAddress is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPandaContainer_Expecter) SchemaRegistryAddress(ctx interface{}) *MockPandaContainer_SchemaRegistryAddress_Call {
	return &MockPandaContainer_SchemaRegistryAddress_Call{Call: _e.mock.On("SchemaRegistryAddress", ctx)}
}

func (_c *MockPandaContainer_SchemaRegistryAddress_Call) Run(run func(ctx context.Context)) *MockPandaContainer_SchemaRegistryAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPandaContainer_SchemaRegistryAddress_Call) Return(s string, err error) *MockPandaContainer_SchemaRegistryAddress_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPandaContainer_SchemaRegistryAddress_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockPandaContainer_SchemaRegistryAddress_Call {
	_c.Call.Return(run)
	return _c
}

// Terminate provides a mock function for the type MockPandaContainer
func (_mock *MockPandaContainer) Terminate(ctx context.Context, opts ...testcontainers.TerminateOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Terminate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...testcontainers.TerminateOption) error); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPandaContainer_Terminate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Terminate'
type MockPandaContainer_Terminate_Call struct {
	*mock.Call
}

// Terminate is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...testcontainers.TerminateOption
func (_e *MockPandaContainer_Expecter) Terminate(ctx interface{}, opts ...interface{}) *MockPandaContainer_Terminate_Call {
	return &MockPandaContainer_Terminate_Call{Call: _e.mock.On("Terminate",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockPandaContainer_Terminate_Call) Run(run func(ctx context.Context, opts ...testcontainers.TerminateOption)) *MockPandaContainer_Terminate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []testcontainers.TerminateOption
		var variadicArgs []testcontainers.TerminateOption
		if len(args) > 1 {
			variadicArgs = args[1].([]testcontainers.TerminateOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockPandaContainer_Terminate_Call) Return(err error) *MockPandaContainer_Terminate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPandaContainer_Terminate_Call) RunAndReturn(run func(ctx context.Context, opts ...testcontainers.TerminateOption) error) *MockPandaContainer_Terminate_Call {
	_c.Call.Return(run)
	return _c
}
